logo: images/max_twitter_headshot.jpg
title: Max Schwarzer
email: MaxA.Schwarzer@gmail.com
description: >-
  Welcome to my personal website! I'm Max Schwarzer, a final-year PhD student in Montreal. I'm passionate about making reinforcement learning more efficient, scalable, and reliable.
  Over the years, my research has led to significant improvements in sample efficiency in deep reinforcement learning, but I'm always aiming higher. Stay tuned for updates!

baseurl: "" # the subpath of your site, e.g. /blog
url: "www.maxschwarzer.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: max_a_schwarzer
github_username:  MaxASchwarzer
google_scholar: https://scholar.google.com/citations?user=YmWRSvgAAAAJ&hl=en

# Build settings
# theme: jekyll-theme-basically-basic
remote_theme: "mmistakes/jekyll-theme-basically-basic@1.4.5"
search: true
lang: en-US
markdown: kramdown
author: 
  name: Max Schwarzer
  twitter: maxaschwarzer
  picture: images/max_twitter_headshot.jpg
plugins:
  - jekyll-feed
  - jekyll-remote-theme # add this line to the plugins list if you already have one

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
